#### Route & Path ####
config:
  host:
    user: http://localhost:7079
    admin: http://localhost:9090
  
  path:
    user: /user/**
    admin: /api/**
  
  publicApi:
    /api/auth/public/backend/login
    /api/auth/public/backend/authStatus
    /api/auth/public/backend/captcha
    /api/auth/public/backend/info

private: 
  get: 
    /api/user/wynne0:
      abc
      123
    /api/user/wynne1:
      cde
      efg
    /api/user/wynne2:
      bbb
      acac
  post:
    /api/user/post3:
    /api/user/post4:
    /api/user/post5:
  put:
    none:
  delete:
    none:
